# 异常

**异常**就是代表程序出现的问题

异常的类型

Error系统异常

Exception编译时异常

RuntimeException运行时异常

**异常体系的最上层父类是谁？异常分为几类？**

父类：Exception

异常分为两类：编译时异常、运行时异常

**编译时异常和运行时异常的区别？**

**编译时异常**：没有继承RuntimeException的异常，直接继承于Exception。编译阶段就会错误提示。

**运行时异常**：RuntimeException本身和子类。编译阶段没有错误提示，运行时出现的。

## 异常的作用

1. 异常时用来查询bug的关键参考信息
2. 异常可以作为方法内部的一种特殊返回值，以便通知调用者底层的执行情况

```java
Student[] arr = new Student[3];
String name = arr[0].getName();
System.out.println(name);
        
// NullPointerException空指针异常，原因，位置
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.haust.test1.Student.getName()" because "arr[0]" is null
	at com.haust.test1.ExceptionDemo1.main(ExceptionDemo1.java:11)
```

```java
Student stu = new Student("张三");
System.out.println(stu);
// ArrayIndexOutOfBoundsException数组越界异常
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.haust.test1.Student.<init>(Student.java:23)
	at com.haust.test1.ExceptionDemo2.main(ExceptionDemo2.java:10)
```

第二点作用的应用示例

```java
public void setAge(int age) {
    if (age < 18 || age > 35) {
        // 年龄超出范围：抛出RuntimeException运行时异常
        throw new RuntimeException();
    } else {
        this.age = age;
    }
}


Student stu = new Student();
stu.setAge(40);

// RuntimeException运行时异常
Exception in thread "main" java.lang.RuntimeException
	at com.haust.test1.Student.setAge(Student.java:65)
	at com.haust.test1.ExceptionDemo2.main(ExceptionDemo2.java:11)
```

## 异常的处理方式

#### JVM默认的处理方案

1. 把异常的名称，原因，出现位置等信息输出到控制台上

2. 程序停止运行，异常下面的代码不会再执行了

#### 自己处理（捕获异常）

格式：

```java
    try {
        可能出现异常的代码;
    }catch (异常类名 变量名){
        异常的处理代码
    }
```

**目的**：**当代码出现问题时，程序不会停止**

```java
int[] arr = {1, 2, 3, 4, 5, 6};

try {
    // 此处出现了异常，程序就会在这里创建一个ArrayIndexOutOfBoundsException对象
    // 拿着这个对象到catch的小括号中对比，看括号中的变量是否可以接收这个对象
    // 如果能被接收，就表示该异常被捕获（抓住），执行catch里面对应的代码
    // 当catch里面所有的代码执行完毕，继续执行try...catch体系下面的其他代码
    System.out.println(arr[10]);
} catch (ArrayIndexOutOfBoundsException e) {
    System.out.println("索引越界");
}
System.out.println("看看我执行了吗？");
// 索引越界
// 看看我执行了吗？
```

## 问题

如果try中没有遇到问题，怎么执行？

```
会把try里面所有的代码执行完毕，不会执行catch
注意： 只有当出现了异常，才会执行catch里面的代码
```

如果try中可能会遇到多个问题，怎么执行？

```
会写多个catch与之对应
细节：
	如果我们要捕获多个异常，这些异常中存在父子关系的话，那么父类一定要写在下面
了解性：
	在JDK7之后，我们可以在catch中同时捕获多个异常，中间用|进行隔开
	表示如果出现了A异常或者B异常的话，采取同一种处理方案
	
```

如果try中遇到的问题没有被捕获，怎么执行？

```
相当于try...catch的代码白写了，最终还是会交给虚拟机进行处理。
异常下面的代码就执行不到了
```

如果try中遇到了问题，那么try下面的代码还会执行吗？

```
下面的代码就不会执行了，直接跳转到对应的catch当中，执行catch里面的语句体
但是如果没有对应的catch与之匹配，那么还是会交给虚拟机进行处理
```

## 异常中的常见方法

public String getMessage()	返回此throwable的详细消息字符串

public String toString()	返回此可抛出的简短描述

public void printStackTrace()	把异常的错误信息输出在控制台

​											细节：

​											仅仅是打印信息，不会停止程序运行

```java
int[] arr = {1, 2, 3, 4, 5, 6};

try {
    System.out.println(arr[10]);
} catch (ArrayIndexOutOfBoundsException e) {
    String message = e.getMessage();
    
    // Index 10 out of bounds for length 6
    System.out.println(message);
    
    String string = e.toString();
    
    // java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6
    System.out.println(string);
    
    // java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 6
    //  at com.haust.test1.ExceptionDemo2.main(ExceptionDemo2.java:14)
    e.printStackTrace();
}
```

## 抛出异常

### throws

注意：

​	写在方法定义处，表示声明一个异常，

​	告诉调用者，使用本方法可能会有哪些异常

```java
public void 方法() throws 异常类名1，异常类名2...{

	...

}
```

编译时异常：必须要写

运行时异常：可以不写

### throw

注意：

​	写在方法内，结束方法

​	手动抛出异常对象，交给调用者

​	方法中下面代码不再执行

```java
public void 方法(){

	throw new NullPointerException();

}
```



```java
public static void main(String[] args) {
//        int[] arr = {1, 2, 3, 4, 5, 6};
//        int[] arr = {};
        int[] arr = null;
        int max = 0;

        try {
            max = getMax(arr);
        } catch (NullPointerException e) {
            System.out.println("空指针异常！！！");
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("索引越界异常");
        }
        System.out.println(max);

    }

    // 方法中存在的问题，传递的数组可能为空，或者长度可能为0
    public static int getMax(int[] arr) /*throws NullPointerException, ArrayIndexOutOfBoundsException*/ {
        if (arr == null) {
            // 手动创建一个异常对象，并把这个异常交给方法的调用者
            // 此时方法就会结束，下面的代码就不会执行了
            throw new NullPointerException();
        }
        if (arr.length == 0) {
            throw new ArrayIndexOutOfBoundsException();
        }
        System.out.println("看看我执行了吗？");
        int max = arr[0];
        for (int i = 0; i < arr.length; i++) {
            if (arr[i] > max) {
                max = arr[i];
            }
        }
        return max;
    }
```

## 练习

```java
/*
需求:
    键盘录入自己心仪的女朋友的姓名和年龄
    姓名的长度在3-10之间，
    年龄范围在18-28之间，
    超出这个范围是异常数据不能被赋值，需要重新录入，一直到录到正确为止。
提示：
    需要考虑用户在键盘录入时的所有情况。
    比如：录入年龄时超出范围，录入年龄时录入abc等情况
 */
Scanner sc = new Scanner(System.in);
MyGirlFriend myGirlFriend = new MyGirlFriend();


while (true) {
    try {
        System.out.println("请输入女朋友姓名：");
        String name = sc.nextLine();
        myGirlFriend.setName(name);

        System.out.println("请输入女朋友年龄：");
        String ageStr = sc.nextLine();
        int age = Integer.parseInt(ageStr);
        myGirlFriend.setAge(age);
        // 如果所有的数据都是正确的，那么跳出循环
        break;
    } catch (NumberFormatException e) {
        System.out.println("年龄的格式有误，请重新录入数字！！！");
        // continue;
    } catch (RuntimeException e) {
        System.out.println("姓名的长度或者年龄的范围有误！！！");
        // continue;
    }
}

System.out.println(myGirlFriend);
```

```java
public class MyGirlFriend {
    private String name;
    private int age;

    public MyGirlFriend() {
    }

    public MyGirlFriend(String name, int age) {
        this.name = name;
        this.age = age;
    }

    /**
     * 获取
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * 设置
     *
     * @param name
     */
    public void setName(String name) {
        if (name.length() < 3 || name.length() > 10) {
            throw new RuntimeException();
        }
        this.name = name;

    }

    /**
     * 获取
     *
     * @return age
     */
    public int getAge() {
        return age;
    }

    /**
     * 设置
     *
     * @param age
     */
    public void setAge(int age) {
        if (age < 18 || age > 28) {
            throw new RuntimeException();
        }
        this.age = age;
    }

    @Override
    public String toString() {
        return "MyGirlFriend{name = " + name + ", age = " + age + "}";
    }
}
```

## 自定义异常

**意义**：**就是为了让控制台的报错信息更加见名知意**

#### ①定义异常类

#### ②写继承关系

#### ③空参构造

#### ④带参构造

NameFormatException

```java
public class NameFormatException extends RuntimeException {
    // 技巧：
    // NameFormat：当前异常的名字，表示姓名格式化问题
    // Exception：表示当前类是一个异常类

    // 运行时异常：RuntimeException
    // 编译时异常：Exception 核心 提醒程序员检查本地信息


    public NameFormatException() {
    }

    public NameFormatException(String message) {
        super(message);
    }
}
```

AgeOutOfBoundsException

```java
public class AgeOutOfBoundsException extends RuntimeException {
    public AgeOutOfBoundsException() {
    }

    public AgeOutOfBoundsException(String message) {
        super(message);
    }
}
```

MyGirlFriend

```java
public class MyGirlFriend {
    private String name;
    private int age;

    public MyGirlFriend() {
    }

    public MyGirlFriend(String name, int age) {
        this.name = name;
        this.age = age;
    }

    /**
     * 获取
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * 设置
     *
     * @param name
     */
    public void setName(String name) {
        if (name.length() < 3 || name.length() > 10) {
            throw new NameFormatException(name + "长度不在范围3-10之间");
        }
        this.name = name;

    }

    /**
     * 获取
     *
     * @return age
     */
    public int getAge() {
        return age;
    }

    /**
     * 设置
     *
     * @param age
     */
    public void setAge(int age) {
        if (age < 18 || age > 28) {
            throw new AgeOutOfBoundsException(age + "不在范围18-28之间");
        }
        this.age = age;
    }

    @Override
    public String toString() {
        return "MyGirlFriend{name = " + name + ", age = " + age + "}";
    }
}

```

main

```java
public static void main(String[] args) {
    /*
    需求:
        键盘录入自己心仪的女朋友的姓名和年龄
        姓名的长度在3-10之间，
        年龄范围在18-28之间，
        超出这个范围是异常数据不能被赋值，需要重新录入，一直到录到正确为止。
    提示：
        需要考虑用户在键盘录入时的所有情况。
        比如：录入年龄时超出范围，录入年龄时录入abc等情况
     */
    Scanner sc = new Scanner(System.in);
    MyGirlFriend myGirlFriend = new MyGirlFriend();


     while (true) {
            try {
                System.out.println("请输入女朋友姓名：");
                String name = sc.nextLine();
                myGirlFriend.setName(name);

                System.out.println("请输入女朋友年龄：");
                String ageStr = sc.nextLine();
                int age = Integer.parseInt(ageStr);
                myGirlFriend.setAge(age);
                // 如果所有的数据都是正确的，那么跳出循环
                break;
            } catch (NumberFormatException | NameFormatException e) {
                e.printStackTrace();
                // continue;
            } catch (AgeOutOfBoundsException e) {
                e.printStackTrace();
            }
        }

        System.out.println(myGirlFriend);

}
```